// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtvC2pEy1iWq23wRE8X_CKe2BkaLGiKRE',
    appId: '1:576258706737:web:5660f5580ef77bf521b410',
    messagingSenderId: '576258706737',
    projectId: 'tripmate-c2ab7',
    authDomain: 'tripmate-c2ab7.firebaseapp.com',
    storageBucket: 'tripmate-c2ab7.appspot.com',
    measurementId: 'G-J9KHTPV32Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfgU8hAV3B5aHog79EWeDhw0Nan0GnkOc',
    appId: '1:576258706737:android:7846ab26563296d521b410',
    messagingSenderId: '576258706737',
    projectId: 'tripmate-c2ab7',
    storageBucket: 'tripmate-c2ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4BqmDXU4QKHK1PrmMZNYu6fuH8etyfk',
    appId: '1:576258706737:ios:0c660eff41a95b1f21b410',
    messagingSenderId: '576258706737',
    projectId: 'tripmate-c2ab7',
    storageBucket: 'tripmate-c2ab7.appspot.com',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk4BqmDXU4QKHK1PrmMZNYu6fuH8etyfk',
    appId: '1:576258706737:ios:0c660eff41a95b1f21b410',
    messagingSenderId: '576258706737',
    projectId: 'tripmate-c2ab7',
    storageBucket: 'tripmate-c2ab7.appspot.com',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtvC2pEy1iWq23wRE8X_CKe2BkaLGiKRE',
    appId: '1:576258706737:web:85ab9be39730d39921b410',
    messagingSenderId: '576258706737',
    projectId: 'tripmate-c2ab7',
    authDomain: 'tripmate-c2ab7.firebaseapp.com',
    storageBucket: 'tripmate-c2ab7.appspot.com',
    measurementId: 'G-5J2ZS8YG2V',
  );
}
